### ISSUE TITLE
Feature: Service or button to clear data

### ISSUE THREAD

**Issue by kotope** [kotope/aio_energy_management#31]
Configuration changes are not effective immediately if expiration time has not been passed. 
This makes experimenting and initial configuration a bit difficult as configuration is refreshed only when nord pool or entso-e data is provided (or after trigger time if used).

Implement a service or button to clear cache for a single sensor or alternatively all data.

**Comment by vanrace** [comment]
I second this! My use-case: 

- I come home with the car.
- HA reads SOC of the EV battery, and calculates how many hours charging it would require to go to 80% or 100% again
- Only then I know the start time, and the hours required.
- Nicest feature would be to just monitor all the attributes, if one or more changes, recalculate. If that becomes too complicated indeed just a service or a button to recalculate would do.

**Comment by kotope** [comment]
Automatic recalculation from attribute changes could cause some side effects, so for the first phase it's a bit too risky. :-)
I'll try to create a service for this functionality for the 0.3.2.

About your use-case you could use trigger_time already, it's kind of implemented for similar situations already. 

Anyhow this lead me thinking, maybe start_time and end_time should be able to set from an input_number (or other) entity as well. As if you want to calculate cheapest hours from e.g. from 18:00 - 09:00 and plug your car in at 20:00. The cheapest hours could have been already from 18:00 to 20:00 and that would have ended up in two missed hours already.

**Comment by vanrace** [comment]
Hi @kotope, thanks for your quick reply. I had overlooked trigger_time, good one, thanks for pointing that out! Is this one dynamic? Can I change it from an automation or something? Because that is what I assumed would be possible with start time and end time, but what I understand now this is probably not the case (yet?)

For the coming home scenario actually first_hour, last_hour and number_of_hours should be settable as a minimum, and there should be a manual recalculate function. Or does it work when first_hours is in the past already? Then I can just set it at the earliest possible.

(if trigger_time is settable that could do the trick, but then you would loose potential valuable time waiting for up to an hour for a re-calculate?)

Anyway, thanks for your thoughts and any further help/comments are appreciated! If you want someone to test or to bounce some ideas of I am available.

**Comment by kotope** [comment]
Hi @vanrace, sorry I've missed your latest comment. Just noticed this as I'm implementing the service and checkout the issue id :-)

With 0.3.1 trigger_hour can be set to be dynamic; start and end times not, but maybe later..

If you have a good idea or enchancement, you could create an enhancement issue.
When passing ideas or asking questions, please use the discussion board so I can keep the issue list more organised and it would be easier to follow (at least for me) :-)

**Comment by kotope** [comment]
Service to clear data is now merged into dev. Will be released with 0.3.2.

**Comment by vanrace** [comment]
Thanks!!

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Toni Korhonen ***@***.***>
Verzonden: Saturday, November 9, 2024 3:30:03 PM
Aan: kotope/aio_energy_management ***@***.***>
CC: vanrace ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [kotope/aio_energy_management] Feature: Service or button to clear data (Issue #31)


Hi @vanrace<https://github.com/vanrace>, sorry I've missed your latest comment. Just noticed this as I'm implementing the service and checkout the issue id :-)

With 0.3.1 trigger_hour can be set to be dynamic; start and end times not, but maybe later..

If you have a good idea or enchancement, you could create an enhancement issue.
When passing ideas or asking questions, please use the discussion board so I can keep the issue list more organised and it would be easier to follow (at least for me) :-)

**Comment by kotope** [comment]
New service to clear data released with 0.3.2
